# Generated by Django 2.2 on 2019-04-17 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rocks', '0002_load_mineral_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mineral',
            name='image_filename',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
